# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/carinterface/listok.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5.uic import loadUi
from PyQt5 import QtWidgets
from PyQt5.QtWidgets import QDialog, QApplication, QFileDialog, QMessageBox,QLabel
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QLabel
from PyQt5.QtCore import Qt, QTimer
from PyQt5.QtGui import QMovie
from car import *
from car2t import *
from car5t import *
from time import sleep
from PyQt5 import uic

class comwin(QDialog):
    def __init__(self, parent, vcarnum):
        super(comwin, self).__init__(parent, vcarnum)
        self.vcarnum = vcarnum
        app = QtWidgets.QApplication(sys.argv)
        Dialog = QtWidgets.QDialog()
        ui = comwin(parent, vcarnum)
        ui.setupUi(Dialog)
        Dialog.show()
        
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(684, 251)
        self.lidia = QtWidgets.QDialogButtonBox(Dialog)
        self.lidia.setGeometry(QtCore.QRect(170, 110, 341, 111))
        font = QtGui.QFont()
        font.setFamily("a고딕17")
        font.setPointSize(46)
        self.lidia.setFont(font)
        self.lidia.setOrientation(QtCore.Qt.Vertical)
        self.lidia.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.lidia.setCenterButtons(True)
        self.lidia.setObjectName("lidia")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 30, 601, 81))
        font = QtGui.QFont()
        font.setFamily("a고딕16")
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.lidia.accepted.connect(Dialog.accept)
        self.lidia.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog, vcarnum):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", vcarnum + "차량<br>감면완료되었습니다"))
        
    
    
comwin()
    